name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run tests in Docker container
        run: docker run playwright-tests

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure_report
          path: reports/

