name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]


jobs:
  # Job for UI tests
  ui_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run UI Tests
        run: |
          pytest ui --alluredir=allure-results  

      - name: Upload Allure report for UI tests
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure_report_ui
          path: ui/allure-results

  # Job for API tests
  api_tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run API Tests
        run: |
          cd api_tests
          pytest --alluredir=allure-results

      - name: Upload API test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: api_test_results
          path: api_tests/allure-results
